name: Go Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history and tags

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build Windows
      env:
        GOOS: windows
        GOARCH: amd64
      run: |
        chmod +x ./scripts/build.sh
        ./scripts/build.sh go-obsidian-ai-sum-windows-am64.exe

    - name: Build Linux
      env:
         GOOS: linux
         GOARCH: amd64
      run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh go-obsidian-ai-sum-linux-am64.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          go-obsidian-ai-sum-windows-am64.exe
          go-obsidian-ai-sum-linux-am64.exe
          